#! /bin/sh

function killbar() {
  if [[ `pidof waybar` ]]; then 
		pkill waybar
  fi
}

function SetRice() {
	case $RICETHEME in
		tokyonight)
		  killbar
		  waybar -c /home/narmis/.config/waybar/tokyonight/config -s /home/narmis/.config/waybar/tokyonight/style.css
		  notify-send changing to tokyonight
		  ;;
			
		superhot)
		  killbar
		  waybar -c /home/narmis/.config/waybar/superhot/config -s /home/narmis/.config/waybar/superhot/style.css
          notify-send changing to superhot
		  ;;		  
	esac		
}
SetRice
